### PR TITLE
Add events to their own collection

### PR DESCRIPTION
**Pull request by danohart**
I tried my hand at more mongo queries since that's not my strong suite. 

@smacmullan let me know what you think slash if I should do this differently. Example of an events document...I also don't really need the name anymore since the conversion script I wrote uses the id/placeId as the vocie of reason..

```{
  "_id": {
    "$oid": "65f47063d387a699edf11e25"
  },
  "placeId": {
    "$oid": "62bf13d3610a170199ad468f"
  },
  "name": "Outside Voices",
  "events": [
    {
      "keywords": "happyHour",
      "lastUpdated": "2022-12-30T15:14:28.968Z",
      "eventSchedule": [
        {
          "byDay": [
            "FR"
          ],
          "startTime": "null",
          "endTime": "null"
        }
      ],
      "menu": [
        {
          "name": "Frozen Cocktails",
          "category": "Drink",
          "price": 8
        },
        {
          "name": "Lambrusco",
          "category": "Drink",
          "price": 6
        },
        {
          "name": "Glass Pours",
          "category": "Drink",
          "price": 8
        },
        {
          "name": " 3-6p"
        }
      ]
    }
  ]
}```

### CODE REVIEW

**Comment by smacmullan** [comment]
I'm not great with MongoDB queries either, but we're learning together!

- When I run seed.js and then createEvents.js., I am getting objects with ids but null "events" fields. Could be me using bad script parameters though.
- I agree, "name" field can be dropped from events. Reference the place Id to get the name
- I'm thinking that, rather than a collection of places' events, we should have one huge event collection with each individual event referencing a place. I haven't thought this through all the way yet, but my gut feel is we'll want to be able to filter on place and time (and maybe recurring vs. one-off events too), and nesting events inside objects might make the time filtering difficult.

I am busy through Wednesday but will take a closer look later this week. Also, Avondale Garden Alliance expressed interest in having a place to easily share their events, and some urbanist folks I've talked to really want a better way to track community meetings (zoning, CDOT hearings, etc.).

**Comment by danohart** [comment]
So maybe instead of 

placeId: Name
events: []

You're proposing more like 

eventName
placeId
eventMenu
eventCategory

so they're be multiple event documents for one place, instead of one place document with associated event array?

**Comment by smacmullan** [comment]
Yep! So the documents in the collection would be close to the Event type I
outlined in the unused definitions.ts file, plus the placeId and a unique
eventId.

**Comment by danohart** [comment]
Conflict. Want to think on this further.

**Pull request closed without merging**
